spring.application.name=WebNoteserver:
  port: 8080
  servlet:
    context-path: /api

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://mysql-db:3306/notesystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: dockerpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/notesystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: dockerpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
