version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: new_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: notesystem
      MYSQL_ROOT_PASSWORD: dockerpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: new_identity_app
    restart: on-failure
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - default

volumes:
  mysql_data:

networks:
  default:
    driver: bridge
